### ISSUE TITLE
Error en tamaño de las imagenes

### ISSUE THREAD

**Issue by mserrano07** [jorgepardor/photofeed#1]
@jorgepardor El tamaño de las imágenes tendría que ser el mismo para todos los post

**Comment by jorgepardor** [comment]
Hola Marcos, he arreglado el css para que las imagenes se enseñen como creo que me pediste. 

En caso de ser una imagen cuadrada, ya funcionaba bien.

En caso de ser una imagen rectangular, ahora lo que hace es ajustar el lado mas grande de la imagen al tamaño del post y aparecen franjas blancas en el lado mas corto. Probé forzando el tamaño de las fotos dentro del tamaño cuadrado, pero eso hace que se pierda parte de la imagen y creo que eso no tiene mucho sentido.

Modifiqué el html para que en las imágenes ocurrieran los 3 casos (y no hacer trampa jaja): una cuadrada, una mas alta que larga y una mas larga que alta. 

Cualquier cosa, me avisas.

Un abrazo,

Jorge
